WebApplication1/Models/Animal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Animal
    {
        public int codigo { get; set; }
        public string nombre { get; set; }
        public string[] sonidos = new string[4];
        //public string[] sonidos { get =>  sonidos; set => sonidos = value; }
    }
}

WebApplication1/Models/SecuenciaNotas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class SecuenciaNotas
    {
        public int codigo { get; set; }
        public string nota { get; set; }
        public int codSigNota { get; set; }
    }
}

WebApplication1/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class AnimalController : Controller
    {
        List<Animal> ListDatos = new List<Animal>();

        // GET: Animal
        public ActionResult Index()
        {
            Animal animal1 = new Animal();
            animal1.codigo = 1;
            animal1.nombre = "rana";
            //{"brr", "birip", "brrah", "croac"}
            animal1.sonidos.SetValue(" brr ",   0);
            animal1.sonidos.SetValue(" birip ", 1); 
            animal1.sonidos.SetValue(" brrah ", 2); 
            animal1.sonidos.SetValue(" croac ", 3);
            ListDatos.Add(animal1);

            Animal animal2 = new Animal();
            animal2.codigo = 2;
            animal2.nombre = "libelula";
            //{"fiu", "plop", "pep"}
            animal2.sonidos.SetValue(" fiu ",  0);
            animal2.sonidos.SetValue(" plop ", 1);
            animal2.sonidos.SetValue(" pep ",  2);
            ListDatos.Add(animal2);

            Animal animal3 = new Animal();
            animal3.codigo = 3;
            animal3.nombre = "grillo";
            //{"cric-cric", "trri-trri", "bri-bri"}
            animal3.sonidos.SetValue(" cric-cric ", 0);
            animal3.sonidos.SetValue(" trri-trri ", 1);
            animal3.sonidos.SetValue(" bri-bri ",   2);
            ListDatos.Add(animal3);

            return View(ListDatos);
        }
    }
}

WebApplication1/Controllers/CancionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CancionController : Controller
    {
        String NotasCancion = "";
        List<SecuenciaNotas> Combinaciones = new List<SecuenciaNotas>();


        public void SiguienteNota(String NotaInicial)
        {
            int pos = -1;
            for (int i = 0; i < Combinaciones.Count(); i++)
            {
                if (String.Equals(Combinaciones.ElementAt(i).nota, NotaInicial))
                {
                    pos = Combinaciones.ElementAt(i).codSigNota;
                    if (pos >= 0)
                        NotasCancion = NotasCancion + Combinaciones.ElementAt(pos).nota + "  ";
                }
            }

            if (pos >= 0)
            {
                NotaInicial = Combinaciones.ElementAt(pos).nota;
                SiguienteNota(NotaInicial);
            }
        }


        // GET: Cancion
        public ActionResult Index(String nota)
        {
            string NotaInicial = nota;

            SecuenciaNotas secuencia1 = new SecuenciaNotas();
            secuencia1.codigo = 0; secuencia1.nota = "brr"; secuencia1.codSigNota = 1;
            Combinaciones.Add(secuencia1);

            SecuenciaNotas secuencia2 = new SecuenciaNotas();
            secuencia2.codigo = 1; secuencia2.nota = "fiu"; secuencia2.codSigNota = 2;
            Combinaciones.Add(secuencia2);

            SecuenciaNotas secuencia3 = new SecuenciaNotas();
            secuencia3.codigo = 2; secuencia3.nota = "cric-cric"; secuencia3.codSigNota = 8;
            Combinaciones.Add(secuencia3);

            SecuenciaNotas secuencia4 = new SecuenciaNotas();
            secuencia4.codigo = 3; secuencia4.nota = "pep"; secuencia4.codSigNota = 4;
            Combinaciones.Add(secuencia4);

            SecuenciaNotas secuencia5 = new SecuenciaNotas();
            secuencia5.codigo = 4; secuencia5.nota = "birip"; secuencia5.codSigNota = 5;
            Combinaciones.Add(secuencia5);

            SecuenciaNotas secuencia6 = new SecuenciaNotas();
            secuencia6.codigo = 5; secuencia6.nota = "trri-trri"; secuencia6.codSigNota = 9;
            Combinaciones.Add(secuencia6);

            SecuenciaNotas secuencia7 = new SecuenciaNotas();
            secuencia7.codigo = 6; secuencia7.nota = "bri-bri"; secuencia7.codSigNota = 7;
            Combinaciones.Add(secuencia7);

            SecuenciaNotas secuencia8 = new SecuenciaNotas();
            secuencia8.codigo = 7; secuencia8.nota = "plop"; secuencia8.codSigNota = 2;
            Combinaciones.Add(secuencia8);

            SecuenciaNotas secuencia9 = new SecuenciaNotas();
            secuencia9.codigo = 8; secuencia9.nota = "brrah"; secuencia9.codSigNota = -1;
            Combinaciones.Add(secuencia9);

            SecuenciaNotas secuencia10 = new SecuenciaNotas();
            secuencia10.codigo = 9; secuencia10.nota = "croac"; secuencia10.codSigNota = -1;
            Combinaciones.Add(secuencia10);

            SiguienteNota(NotaInicial);

            ViewData["cancion"] = NotasCancion;

            return View();
        }



    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {

            return View();
        }
    }
}

WebApplication1/Views/Animal/Index.cshtml
@model IEnumerable<WebApplication1.Models.Animal>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Listado de sonidos</title>
</head>
<body>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.sonidos)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.sonidos)
                </td>
            </tr>
        }

    </table>

    <div>
        <form id="form" method="post" action="/Animal/Index">
            <p> @Html.ActionLink("Desea Reproducir Cancion?", "Index", "Cancion", new { nota = "pep" }, null) </p>

        </form>
    </div>

</body>
</html>

WebApplication1/Views/Cancion/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Reproduciendo cancion...</title>
</head>
<body>
    <div>
        <h1>Cancion...</h1>
        <hr />
        <hr />
        Notas: <b> @ViewData["cancion"] </b> .

    </div>
</body>
</html>

WebApplication1/Views/Home/Index.cshtml
<div class="jumbotron">
    <h2>Inicio Test</h2>
</div>
<div class="row">
    <div class="col-md-4">
        <u1 id="menu">
            <li> @Html.ActionLink("Ver Informacion", "Index", "Animal") </li>
        </u1>

    </div>
    @section footer{
        <p class="lead"> By Jhoselyn Zambrano S. </p>
    }
</div>